#!/bin/bash

# Setup preferences (requires restart)
./preferences

# Install applications
./install

echo "Done! You're all set up and ready to go. You may need to restart your computer"

read -rp 'Would you like to restart the computer now? [y/N]' response

if [[ $response =~ (yes|y|Y) ]];then
	sudo shutdown -r now;
fi