#!/bin/bash

echo 'Tweaking your preferences for macOS'
./macos.sh

echo 'Installing applications'
./install.sh

echo 'Setting up login items'
./login-items.sh

echo 'Stowing your .files to $HOME'
ls -d */ | xargs stow -vv

echo 'Restoring from Mackup'
mackup restore

echo 'All done! You may need to restart your computer'
./restart.sh
